baseURL = "https://digitalsoba.github.io/classroom-profiles-ops/"
languageCode = "en-us"
title = "Classroom Profiles docs"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
publishDir = "../docs"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]