version: '3'

services:
  webserver:
    container_name: classroom-profiles
    image: ainlavong/classroom-profiles
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html

  composer:
    restart: 'no'
    container_name: composer_install
    image: composer:latest
    command: install
    volumes:
      - .:/app/
