---
- name: Add RPM GPG key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add Elastic repo
  yum_repository:
    name: Elastic 
    description: repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgcakey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    setype: rpm-md

- name: Install Beats
  yum:
    name: filebeat
    state: present

- name: Add filebeat.yml config
  template:
    src: filebeat.yml
    dest: /etc/filebeat/
  notify: Restart filebeat

- name: Enable filebeat modules
  command: filebeat modules enable "{{ item }}"
  with_items:
    - system
    - nginx
  notify:
    - Start and enable filebeat

