version: '3'

services:
  drone:
    container_name: drone
    image: 'drone/drone:1.0.0-rc.1'
    restart: always
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/var/lib/drone:/data'
    environment:
        - DRONE_GITHUB_SERVER=https://github.com
        - DRONE_GITHUB_CLIENT_ID=$CLIENT_ID
        - DRONE_GITHUB_CLIENT_SECRET=$CLIENT_SECRET
        - DRONE_RUNNER_CAPACITY=2
        - DRONE_SERVER_HOST=$SERVER_HOST
        - DRONE_SERVER_PROTO=https
        - DRONE_TLS_AUTOCERT=true
        - DRONE_USER_FILTER=CSUN-Comp490, digitalsoba
        - DRONE_USER_CREATE=username:digitalsoba,machine:false,admin:true