---
- name: Clone dev project
  when: stage == "dev"
  git:
    repo: https://github.com/CSUN-Comp490/classroom-profiles.git
    dest: /var/www/{{ stage }}/laravel
    version: dev

- name: Clone master project
  when: stage == "prod"
  git:
    repo: https://github.com/CSUN-Comp490/classroom-profiles.git
    dest: /var/www/{{ stage }}/laravel
    version: master

- name: Composer install
  composer:
    command: install
    working_dir: /var/www/{{ stage }}/laravel

- name: Copy prod .env
  when: stage == "prod"
  copy:
    src: prod
    dest: /var/www/{{ stage }}/laravel/.env

- name: Copy dev .env
  when: stage == "dev"
  copy:
    src: dev
    dest: /var/www/{{ stage }}/laravel/.env        

- name: Generate app key
  command: php artisan key:generate
  args:
    chdir: /var/www/{{ stage }}/laravel

- name: Change laravel permission
  file:
    path: /var/www/{{ stage }}/laravel
    owner: www-data
    group: www-data
    recurse: yes

- name: Create symlink
  file:
    src: /var/www/{{ stage }}/laravel/public
    dest: /var/www/{{ stage }}/public
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted