---
- name: Install php-nginx modules
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - composer
      - php7.2 
      - php7.2-curl 
      - php7.2-common 
      - php7.2-cli 
      - php7.2-mysql 
      - php7.2-mbstring 
      - php7.2-fpm 
      - php7.2-xml 
      - php7.2-zip 
      - unzip
      - zip

- name: Change php7.2-fpm cgi.fix_pathinfo=0
  lineinfile: 
    path: /etc/php/7.2/fpm/php.ini 
    regexp: '^(.*)cgi.fix_pathinfo=' 
    line: cgi.fix_pathinfo=0
  notify: 
   - restart php7.2-fpm
   - enable php7.2-fpm