---
- name: Install php + modules
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - composer  
    - php7.2
    - libapache2-mod-php7.2
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xmlrpc
    - php7.2-soap
    - php7.2-gd
    - php7.2-xml
    - php7.2-cli
    - php7.2-zip
    - php7.2-ldap