---
- name: Enable elk services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - elasticsearch
    - kibana
    - logstash

- name: Start elk services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - elasticsearch
    - kibana
    - logstash

- name: Restart nginx
  service:
    name: nginx
    state: restarted