# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Ubuntu 18.04 box
  config.vm.box = "bento/ubuntu-18.04"

  # Use a local IP Address
  config.vm.network "private_network", ip: "192.168.33.10"

  # Set RAM to 512 mb
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus   = "2"
  end

  # Provision with ansible playbook
  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "kube-dependencies.yml"
  end	
end