---
- name: Update the repository cache on Ubuntu
  apt: 
    update_cache: true

- name: Install nginx
  apt: 
    name: nginx
    state: present 

- name: Copy dev nginx config 
  when: stage == "dev"
  template:
    src: dev.j2
    dest: /etc/nginx/sites-available/{{ stage }}

- name: Copy production nginx config 
  when: stage == "prod"
  template:
    src: prod.j2
    dest: /etc/nginx/sites-available/{{ stage }}

- name: Remove default syslink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create syslink
  file:
    src: /etc/nginx/sites-available/{{ stage }}
    dest: /etc/nginx/sites-enabled/{{ stage }}
    state: link
  notify: restart nginx