---
- name: Update the repository cache on Ubuntu
  apt: 
    update_cache: true

- name: Install nginx
  apt: 
    name: nginx
    state: present 

- name: Copy nginx config
  template:
    src: laravel.j2
    dest: /etc/nginx/sites-available/{{ env }}

- name: Remove default syslink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create syslink
  file:
    src: /etc/nginx/sites-available/{{ env }}
    dest: /etc/nginx/sites-enabled/{{ env }}
    state: link
  notify: restart nginx