---

- name: Install add-apt-repostory
  become: yes
  apt: 
    name: software-properties-common 
    state: latest
  vars:
    packages:
        - apt-transport-https
        - openjdk-11-jdk
        - software-properties-common 

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic source list
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Update apt cache and install stack
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - elasticsearch
      - kibana
      - nginx
      - logstash
      - filebeat

- name: Add elasticsearch yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Add Logstash pipelines
  template:
    src: "{{ item.src }}"
    dest: /etc/logstash/conf.d/
  with_items:
    - {src: 02-beats-input.conf}
    - {src: 10-syslog-filter.conf}
    - {src: 11-apache2-filter.conf}
    - {src: 12-nginx-filter.conf}
    - {src: 30-elasticsearch-output.conf}
    
- name: Start Elastic Stack
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - elasticsearch
    - kibana
    - logstash

- name: Wait for elasticsearch to start
  wait_for:
    port: 9200
    delay: 60

- name: Add htpassword.users files
  copy:
    src: htpasswd.users
    dest: /etc/nginx/htpasswd.users

- name: Add nginx kibana proxy template
  template: 
    src: nginx.default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart-nginx
