
--- 
- name: Update the repository cache on Ubuntu
  become: true
  apt: 
    update_cache: true

- name: Install Docker dependencies 
  become: true
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - apache2-utils
        - apt-transport-https
        - ca-certificates 
        - curl
        - software-properties-common
        - unzip
        - zip

- name: Add Docker's official GPG key
  become: true 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Stable Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: true 

- name: Install docker-ce=18.06.3~ce~3-0~ubuntu
  apt:
    name: docker-ce=18.06.3~ce~3-0~ubuntu
    state: present 
    update_cache: true 

- name: Install containerd.io
  apt:
    name: containerd.io
    state: present

- name: Enable docker on systemd
  systemd:
    name: docker
    enabled: yes
    
- name: Install docker-compose with curl
  become: true
  shell: curl -L https://github.com/docker/compose/releases/download/1.24.0-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

- name: Allow docker-compose execute
  file:
    path: /usr/local/bin/docker-compose
    mode: "+x"
 
- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - anthony
    
