---
- name: Check if sudo is present
  group: 
    name: sudo
    state: present 

- name: Create users and add to sudo
  user:
    name: "{{ item }}"
    state: present
    groups: sudo
    shell: /bin/bash
    createhome: yes
  with_items:
    - anthony
    - envoy
  
- name: Set pubkey for anthony
  authorized_key: 
    user: anthony
    state: present
    key: https://github.com/digitalsoba.keys

- name: Sudoless password
  lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'